### PR TITLE
Sanity tests: copy ignore-2.13.txt to ignore-2.14.txt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/news-for-maintainers/issues/13

Dear maintainers,

I'd like to ask you to track the news-for-maintainers themselves in the future if possible

Thanks!

### CODE REVIEW

**Comment by Andersson007** [comment]
@goneri @gravesm i created gate label and put but it doesn't seem work here

**Comment by goneri** [comment]
Hi @Andersson007,

Follow up to the recent CI migration, the label should now be called `mergeit`.

**Comment by Andersson007** [comment]
@goneri ah, got it, thanks!

**Comment by goneri** [comment]
regate

**Comment by Andersson007** [comment]
@goneri thanks!

**Pull request merged**
