### PR TITLE
EmbeddedModuleFailure - Honor kwargs

### LINKED ISSUE #55: Module failure push ``kwargs`` to core as string instead of dictionnary
``AnsibleTurboModule`` class implements ``fail_json`` like this
 
https://github.com/ansible-collections/cloud.common/blob/e620e72f0f28e9b9fa2aee12c375155949e012fa/plugins/module_utils/turbo/module.py#L174-L179

https://github.com/ansible-collections/cloud.common/blob/e620e72f0f28e9b9fa2aee12c375155949e012fa/plugins/module_utils/turbo/exceptions.py#L1-L5

The exception raised with be converted into one single message.
Assuming you are trying to fail with the following information 

```
{'changed': True, 'result': {...}, 'duration': 10, 'method': 'create'} and msg="Resource creation timed out"
```
The task output will be similar to this 

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Resource creation timed out{'changed': True, 'result':{...}, 'duration': 10, 'method': 'create'}"}
```

### EXPECTED RESULTS
```
fatal: [localhost]: FAILED! => {"changed": true, "msg": "Resource creation timed out", "duration": 10, "method": "create"}
```

##### SUMMARY

The ``EmbeddedModuleFailure`` is basically concatenating the ``msg`` with the ``kwargs`` (convert into a string) arguments to build the exception message

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

AnsibleTurboModule

### PR DESCRIPTION
**Pull request by abikouo**
Depends-On: https://github.com/ansible-collections/cloud.common/pull/57
Depends-On: https://github.com/ansible-collections/vmware.vmware_rest/pull/207

##### SUMMARY

closes #55 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

EmbeddedModuleFailure

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by goneri** [comment]
Sighs... I'm working on the license issue.

**Comment by goneri** [comment]
recheck

**Pull request merged**
